fix(print): fix print for NullLiteral
ember-template-lint/ember-template-recast pull request #725
Opened 2022-01-10 21:05 UTC by VincentMolinie

2022-01-11 11:20 UTC, VincentMolinie commented
@dcyriller may be you can help me 👼

2022-01-11 19:11 UTC, bmish commented on package.json
> +    "test:jest": "npx jest"
Need to remove `npx` from all of these.

2022-01-11 21:51 UTC, dcyriller commented on src/parse-result.ts
> +            source = ast.value?.toString() || '';
I would expect `ast` to always have a value. So I don't understand why we need the optional chaining and the fallback. If it is really needed, could you add a test case?

2022-01-11 21:56 UTC, dcyriller commented on src/parse-result.ts
> +            source = ast.value?.toString() || '';
I realize it may be related to the first commit: https://github.com/ember-template-lint/ember-template-recast/pull/725/commits/be1b4c3d989e2df879e35d3c2d1e47b9293146cf ("fix(typescript): fix typescript configuration"). Do you mind opening a different PR for this commit? As it triggers some discussion, we can keep the discussion there and merge "fix print for NullLiteral".

2022-01-12 07:22 UTC, VincentMolinie commented on src/parse-result.ts
> +            source = ast.value?.toString() || '';
Yes of course

2022-01-12 07:47 UTC, VincentMolinie commented on src/parse-result.ts
> +            source = ast.value?.toString() || '';
Done 👍

2022-01-12 14:22 UTC, bmish approved these changes

2022-01-12 14:22 UTC, bmish commented on src/parse-result.test.ts
> +  describe('NullLitteral', function () {
```suggestion
  describe('NullLiteral', function () {
```

2022-01-12 14:23 UTC, bmish commented on src/parse-result.ts
> +            source = ast.value?.toString() || '';
Test is still failing now?

> Error: src/parse-result.ts(1117,22): error TS2531: Object is possibly 'null'.

2022-01-12 15:01 UTC, VincentMolinie commented on src/parse-result.ts
> +            source = ast.value?.toString() || '';
Should be good now @bmish 😉

2022-01-12 16:58 UTC, VincentMolinie commented
It's never passing into my code. My test is actually wrong 😞

2022-01-12 19:05 UTC, VincentMolinie commented
I finally found a way to reproduce the issue. It's when you are deleting or setting something on the node `NullLiteral`. in my case I was doing a `delete node._globalNode`

2022-01-12 21:47 UTC, rwjblue requested changes

2022-01-12 21:47 UTC, rwjblue commented on src/parse-result.test.ts
> +} from '@glimmer/syntax/dist/types/lib/v1/nodes-v1';
Can we get these from the already imported `AST` from just above?

2022-01-12 21:47 UTC, rwjblue commented on src/parse-result.test.ts
> +        ></div>`;
The spacing changes seem unrelated, can you reset them?

2022-01-12 21:47 UTC, rwjblue commented on src/parse-result.test.ts
> +
I think this should be the only change to this file (once all the unrelated whitespace changes are reverted), right?

2022-01-13 08:19 UTC, VincentMolinie commented on src/parse-result.test.ts
> +} from '@glimmer/syntax/dist/types/lib/v1/nodes-v1';
Oh sorry it's on automatic import, did not notice

2022-01-13 08:32 UTC, VincentMolinie commented on src/parse-result.test.ts
> +} from '@glimmer/syntax/dist/types/lib/v1/nodes-v1';
Done 👍

2022-01-13 16:10 UTC, rwjblue approved these changes

2022-01-13 18:12 UTC, VincentMolinie commented
I can't merge. I let you do it 👼

2022-01-13 20:17 UTC, dcyriller approved these changes

2022-01-14 10:15 UTC, VincentMolinie commented
@bmish can you merge it and create a patch ? 🙏

2022-01-14 12:07 UTC, bmish commented
@dcyriller want to release it? If you can't get to it, I might be able to try later today.

2022-01-14 22:07 UTC, merged

2022-01-14 22:19 UTC, dcyriller commented
It is released in [v6.1.3](https://github.com/ember-template-lint/ember-template-recast/releases/tag/v6.1.3)